import "server-only";
import { mkdir, readdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import type { CaseRecord } from "@/lib/domain/case";
import type { QuoteRecord } from "@/lib/desks/quotes/record";
import type { OrderRecord } from "@/lib/desks/orders/record";

/**
 * Record storage, one namespace per desk.
 *
 * Reads are served from an in-memory index so a list page never touches the
 * disk, and writes go through to JSON files so a record survives a restart —
 * which matters, because a run takes minutes and losing it to a stray Ctrl-C
 * is infuriating.
 *
 * On a read-only or ephemeral filesystem the disk half is skipped and the
 * index is all there is. That is stated on the list pages rather than
 * pretended away; see `isPersistent`.
 */
export interface RecordStore<T> {
  get(id: string): Promise<T | null>;
  put(record: T): Promise<void>;
  list(): Promise<T[]>;
  remove(id: string): Promise<void>;
}

type Stored = { id: string; createdAt: string };

/**
 * Serverless filesystems are read-only apart from a per-instance temp
 * directory, so persisting there would promise more than it delivers. Opt in
 * explicitly if you have mounted real storage.
 */
const persistent =
  process.env.SECOND_CHAIR_PERSIST === "1" ||
  (!process.env.VERCEL && process.env.SECOND_CHAIR_PERSIST !== "0");

const dataRoot =
  process.env.SECOND_CHAIR_DATA_DIR ?? path.join(process.cwd(), ".data");

export function isPersistent(): boolean {
  return persistent;
}

export function dataDirectory(): string {
  return dataRoot;
}

const globalRef = globalThis as typeof globalThis & {
  __secondChairStores?: Map<string, Map<string, unknown>>;
  __secondChairLoaded?: Set<string>;
};

// Survives hot reloads in development, which would otherwise drop the index
// (and re-read every file) on each save.
const namespaces = (globalRef.__secondChairStores ??= new Map());
const hydrated = (globalRef.__secondChairLoaded ??= new Set());

/** Ids are generated by us and must never escape their namespace directory. */
function safeId(id: string): string | null {
  return /^[A-Za-z0-9_-]{1,128}$/.test(id) ? id : null;
}

export function createStore<T extends Stored>(namespace: string): RecordStore<T> {
  const index = (namespaces.get(namespace) ??
    namespaces.set(namespace, new Map()).get(namespace)!) as Map<string, T>;
  const dir = path.join(dataRoot, namespace);

  /** Reads whatever is on disk into the index, once per process. */
  async function hydrate(): Promise<void> {
    if (hydrated.has(namespace)) return;
    hydrated.add(namespace);
    if (!persistent) return;

    let files: string[];
    try {
      files = await readdir(dir);
    } catch {
      return; // nothing has been written yet
    }

    for (const file of files) {
      if (!file.endsWith(".json")) continue;
      try {
        const raw = await readFile(path.join(dir, file), "utf8");
        const record = JSON.parse(raw) as T;
        if (record?.id) index.set(record.id, record);
      } catch {
        // A half-written or hand-edited file must not take the desk down.
      }
    }
  }

  async function persist(record: T): Promise<void> {
    if (!persistent) return;
    const id = safeId(record.id);
    if (!id) return;

    try {
      await mkdir(dir, { recursive: true });
      // Write beside the target and rename, so a crash mid-write cannot leave
      // a truncated record where a valid one used to be.
      const target = path.join(dir, `${id}.json`);
      const temp = `${target}.${process.pid}.tmp`;
      await writeFile(temp, JSON.stringify(record, null, 2), "utf8");
      await rename(temp, target);
    } catch {
      // Storage is a convenience here, not a correctness requirement: the
      // index already has the record and the run must not fail over this.
    }
  }

  return {
    async get(id) {
      await hydrate();
      return index.get(id) ?? null;
    },
    async put(record) {
      await hydrate();
      index.set(record.id, record);
      await persist(record);
    },
    async list() {
      await hydrate();
      return [...index.values()].sort((a, b) =>
        b.createdAt.localeCompare(a.createdAt),
      );
    },
    async remove(id) {
      await hydrate();
      index.delete(id);
      const safe = safeId(id);
      if (!persistent || !safe) return;
      try {
        await rm(path.join(dir, `${safe}.json`), { force: true });
      } catch {
        /* already gone */
      }
    },
  };
}

export const caseStore = createStore<CaseRecord>("cases");
export const quoteStore = createStore<QuoteRecord>("quotes");
export const orderStore = createStore<OrderRecord>("orders");

/** Ids carry their desk, so a stray id is obvious in a log or a URL. */
export function newId(prefix: string): string {
  return `${prefix}_${Date.now().toString(36)}${Math.random().toString(36).slice(2, 7)}`;
}

export const newCaseId = () => newId("case");
export const newQuoteId = () => newId("quote");
export const newOrderId = () => newId("order");
